.TH "CBUFFTYPE" 3 "Mon Oct 24 2011" "CBUFF-Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBUFFTYPE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "CBUFF * \fBstartOfBuffer\fP"
.br
.ti -1c
.RI "CBUFF * \fBendOfBuffer\fP"
.br
.ti -1c
.RI "CBUFF * \fBinPointer\fP"
.br
.ti -1c
.RI "CBUFF * \fBoutPointer\fP"
.br
.ti -1c
.RI "CBUFFNUM \fBbufferNumber\fP"
.br
.ti -1c
.RI "unsigned char \fBlocalFlag\fP"
.br
.ti -1c
.RI "struct \fBCBUFFTYPE\fP * \fBnextCircBufferObj\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CBUFF-Module from the source code.
